# 01 - Carregamento e Preparação de Dados

Este notebook usa a configuração em YAML e os módulos do framework `model_supermarket` para carregar, normalizar e salvar a base de notas fiscais.

In [1]:
# Última nota no Nota Paraná: 15/06/2026

In [2]:
# !pip install -r requirements.txt

In [3]:
# IMPORTS
from pathlib import Path
import time
from src.core.config_loader import ConfigLoader
from src.core.tictoc import tictoc
from src.core.nfce_fetcher import run_nfce_fetch, process_base

# CONFIGURAÇÃO
tic_geral = time.time()
config = ConfigLoader("config/config.yaml")
qrcodes_path = Path(config.get('data.qrcodes_path'))
fetched_path = Path(config.get('data.fetched_data_path'))
mapping_path = Path(config.get('data.qrcode_mapping_path'))
raw_path = Path(config.get('data.raw_invoice_path'))
FETCH_REAL_DATA = config.get('data_fetching.enabled')
FETCH_REAL_DATA_TRAT = config.get('data_fetching.enabled_trat')
FETCH_DELAY = config.get('data_fetching.delay_between_requests')
WEATHER_ENABLED = config.get('external_data.weather.enabled')
WEATHER_OUTPUT_PATH = config.get('external_data.weather.output_path')
WEATHER_LATITUDE = config.get('external_data.weather.latitude')
WEATHER_LONGITUDE = config.get('external_data.weather.longitude')

## 1. Carregamento dos Dados

In [4]:
tic = time.time()

### 1.1 Busca no Site da Fazenda

**📦 `run_nfce_fetch`**

**📖 Descrição**

Função responsável por **buscar, extrair e estruturar dados de NFC-e a partir de QR Codes**, gerando uma base consolidada de itens de notas fiscais.

---

**⚙️ Parâmetros**

| Parâmetro       | Tipo    | Descrição                                                                |
| --------------- | ------- | ------------------------------------------------------------------------ |
| `fetch_enabled` | `bool`  | Se `True`, realiza a busca das notas. Se `False`, lê o CSV já existente. |
| `delay`         | `float` | Tempo de espera entre requisições.                                       |
| `qrcodes_path`  | `Path`  | Arquivo com os QR Codes (um por linha).                                  |
| `fetched_path`  | `Path`  | Caminho do CSV final gerado/lido.                                        |
| `mapping_path`  | `Path`  | Caminho do CSV de mapeamento da anonimização.                            |

---

**🔁 Comportamento**

**🔹 `fetch_enabled = False`**

* Lê o CSV existente (`fetched_path`)
* Retorna a base sem processamento

**🔹 `fetch_enabled = True`**

Executa as seguintes etapas:

* **Lê e remove QR Codes duplicados**
* **Consulta cada QR Code** (via API)
* **Extrai itens da nota**
* **Padroniza colunas** (schema final)
* **Converte e valida valores numéricos**
* **Enriquece com dados da nota**:

  * supermercado
  * CNPJ
  * data
  * totais
* **Anonimiza a chave da NFC-e** (SHA256)
* **Gera tabela de mapeamento (de_para)**
* **Consolida todas as notas em um único DataFrame**
* **Padroniza nome dos produtos (associar maior código ao nome mais recente)**
* **Organiza colunas finais**
* **Salva em CSV**

---

**📤 Retorno**

`pd.DataFrame` com os itens das notas fiscais processadas.

### 1.2 Execução

In [5]:
df_fetched = run_nfce_fetch(
    FETCH_REAL_DATA,
    FETCH_DELAY,
    qrcodes_path,
    fetched_path,
    mapping_path,
)

Configuração de busca (nfceget): FETCH_REAL_DATA=True
ℹ QR Codes únicos: 201
[1/201] Buscando... ✅ Nota obtida
[2/201] Buscando... ✅ Nota obtida
[3/201] Buscando... ✅ Nota obtida
[4/201] Buscando... ✅ Nota obtida
[5/201] Buscando... ✅ Nota obtida
[6/201] Buscando... ✅ Nota obtida
[7/201] Buscando... ✅ Nota obtida
[8/201] Buscando... ✅ Nota obtida
[9/201] Buscando... ✅ Nota obtida
[10/201] Buscando... ✅ Nota obtida
[11/201] Buscando... ✅ Nota obtida
[12/201] Buscando... ✅ Nota obtida
[13/201] Buscando... ✅ Nota obtida
[14/201] Buscando... ✅ Nota obtida
[15/201] Buscando... ✅ Nota obtida
[16/201] Buscando... ✅ Nota obtida
[17/201] Buscando... ✅ Nota obtida
[18/201] Buscando... ✅ Nota obtida
[19/201] Buscando... ✅ Nota obtida
[20/201] Buscando... ✅ Nota obtida
[21/201] Buscando... ✅ Nota obtida
[22/201] Buscando... ✅ Nota obtida
[23/201] Buscando... ✅ Nota obtida
[24/201] Buscando... ✅ Nota obtida
[25/201] Buscando... ✅ Nota obtida
[26/201] Buscando... ✅ Nota obtida
[27/201] Buscando... ✅ Nota obtida
[28/201] Buscando... ✅ Nota obtida
[29/201] Buscando... ✅ Nota obtida
[30/201] Buscando... ✅ Nota obtida
[31/201] Buscando... ✅ Nota obtida
[32/201] Buscando... ✅ Nota obtida
[33/201] Buscando... ✅ Nota obtida
[34/201] Buscando... ✅ Nota obtida
[35/201] Buscando... ✅ Nota obtida
[36/201] Buscando... ✅ Nota obtida
[37/201] Buscando... ✅ Nota obtida
[38/201] Buscando... ✅ Nota obtida
[39/201] Buscando... ✅ Nota obtida
[40/201] Buscando... ✅ Nota obtida
[41/201] Buscando... ✅ Nota obtida
[42/201] Buscando... ✅ Nota obtida
[43/201] Buscando... ✅ Nota obtida
[44/201] Buscando... ✅ Nota obtida
[45/201] Buscando... ✅ Nota obtida
[46/201] Buscando... ✅ Nota obtida
[47/201] Buscando... ✅ Nota obtida
[48/201] Buscando... ✅ Nota obtida
[49/201] Buscando... ✅ Nota obtida
[50/201] Buscando... ✅ Nota obtida
[51/201] Buscando... ✅ Nota obtida
[52/201] Buscando... ✅ Nota obtida
[53/201] Buscando... ✅ Nota obtida
[54/201] Buscando... ✅ Nota obtida
[55/201] Buscando... ✅ Nota obtida
[56/201] Buscando... ✅ Nota obtida
[57/201] Buscando... ✅ Nota obtida
[58/201] Buscando... ✅ Nota obtida
[59/201] Buscando... ✅ Nota obtida
[60/201] Buscando... ✅ Nota obtida
[61/201] Buscando... ✅ Nota obtida
[62/201] Buscando... ✅ Nota obtida
[63/201] Buscando... ✅ Nota obtida
[64/201] Buscando... ✅ Nota obtida
[65/201] Buscando... ✅ Nota obtida
[66/201] Buscando... ✅ Nota obtida
[67/201] Buscando... ✅ Nota obtida
[68/201] Buscando... ✅ Nota obtida
[69/201] Buscando... ✅ Nota obtida
[70/201] Buscando... ✅ Nota obtida
[71/201] Buscando... ✅ Nota obtida
[72/201] Buscando... ✅ Nota obtida
[73/201] Buscando... ✅ Nota obtida
[74/201] Buscando... ✅ Nota obtida
[75/201] Buscando... ✅ Nota obtida
[76/201] Buscando... ✅ Nota obtida
[77/201] Buscando... ✅ Nota obtida
[78/201] Buscando... ✅ Nota obtida
[79/201] Buscando... ✅ Nota obtida
[80/201] Buscando... ✅ Nota obtida
[81/201] Buscando... ✅ Nota obtida
[82/201] Buscando... ✅ Nota obtida
[83/201] Buscando... ✅ Nota obtida
[84/201] Buscando... ✅ Nota obtida
[85/201] Buscando... ✅ Nota obtida
[86/201] Buscando... ✅ Nota obtida
[87/201] Buscando... ✅ Nota obtida
[88/201] Buscando... ✅ Nota obtida
[89/201] Buscando... ✅ Nota obtida
[90/201] Buscando... ✅ Nota obtida
[91/201] Buscando... ✅ Nota obtida
[92/201] Buscando... ✅ Nota obtida
[93/201] Buscando... ✅ Nota obtida
[94/201] Buscando... ✅ Nota obtida
[95/201] Buscando... ✅ Nota obtida
[96/201] Buscando... ✅ Nota obtida
[97/201] Buscando... ✅ Nota obtida
[98/201] Buscando... ✅ Nota obtida
[99/201] Buscando... ✅ Nota obtida
[100/201] Buscando... ✅ Nota obtida
[101/201] Buscando... ✅ Nota obtida
[102/201] Buscando... ✅ Nota obtida
[103/201] Buscando... ✅ Nota obtida
[104/201] Buscando... ✅ Nota obtida
[105/201] Buscando... ✅ Nota obtida
[106/201] Buscando... ✅ Nota obtida
[107/201] Buscando... ✅ Nota obtida
[108/201] Buscando... ✅ Nota obtida
[109/201] Buscando... ✅ Nota obtida
[110/201] Buscando... ✅ Nota obtida
[111/201] Buscando... ✅ Nota obtida
[112/201] Buscando... ✅ Nota obtida
[113/201] Buscando... ✅ Nota obtida
[114/201] Buscando... ✅ Nota obtida
[115/201] Buscando... ✅ Nota obtida
[116/201] Buscando... ✅ Nota obtida
[117/201] Buscando... ✅ Nota obtida
[118/201] Buscando... ✅ Nota obtida
[119/201] Buscando... ✅ Nota obtida
[120/201] Buscando... ✅ Nota obtida
[121/201] Buscando... ✅ Nota obtida
[122/201] Buscando... ✅ Nota obtida
[123/201] Buscando... ✅ Nota obtida
[124/201] Buscando... ✅ Nota obtida
[125/201] Buscando... ✅ Nota obtida
[126/201] Buscando... ✅ Nota obtida
[127/201] Buscando... ✅ Nota obtida
[128/201] Buscando... ✅ Nota obtida
[129/201] Buscando... ✅ Nota obtida
[130/201] Buscando... ✅ Nota obtida
[131/201] Buscando... ✅ Nota obtida
[132/201] Buscando... ✅ Nota obtida
[133/201] Buscando... ✅ Nota obtida
[134/201] Buscando... ✅ Nota obtida
[135/201] Buscando... ✅ Nota obtida
[136/201] Buscando... ✅ Nota obtida
[137/201] Buscando... ✅ Nota obtida
[138/201] Buscando... ✅ Nota obtida
[139/201] Buscando... ✅ Nota obtida
[140/201] Buscando... ✅ Nota obtida
[141/201] Buscando... ✅ Nota obtida
[142/201] Buscando... ✅ Nota obtida
[143/201] Buscando... ✅ Nota obtida
[144/201] Buscando... ✅ Nota obtida
[145/201] Buscando... ✅ Nota obtida
[146/201] Buscando... ✅ Nota obtida
[147/201] Buscando... ✅ Nota obtida
[148/201] Buscando... ✅ Nota obtida
[149/201] Buscando... ✅ Nota obtida
[150/201] Buscando... ✅ Nota obtida
[151/201] Buscando... ✅ Nota obtida
[152/201] Buscando... ✅ Nota obtida
[153/201] Buscando... ✅ Nota obtida
[154/201] Buscando... ✅ Nota obtida
[155/201] Buscando... ✅ Nota obtida
[156/201] Buscando... ✅ Nota obtida
[157/201] Buscando... ✅ Nota obtida
[158/201] Buscando... ✅ Nota obtida
[159/201] Buscando... ✅ Nota obtida
[160/201] Buscando... ✅ Nota obtida
[161/201] Buscando... ✅ Nota obtida
[162/201] Buscando... ✅ Nota obtida
[163/201] Buscando... ✅ Nota obtida
[164/201] Buscando... ✅ Nota obtida
[165/201] Buscando... ✅ Nota obtida
[166/201] Buscando... ✅ Nota obtida
[167/201] Buscando... ✅ Nota obtida
[168/201] Buscando... ✅ Nota obtida
[169/201] Buscando... ✅ Nota obtida
[170/201] Buscando... ✅ Nota obtida
[171/201] Buscando... ✅ Nota obtida
[172/201] Buscando... ✅ Nota obtida
[173/201] Buscando... ✅ Nota obtida
[174/201] Buscando... ✅ Nota obtida
[175/201] Buscando... ✅ Nota obtida
[176/201] Buscando... ✅ Nota obtida
[177/201] Buscando... ✅ Nota obtida
[178/201] Buscando... ✅ Nota obtida
[179/201] Buscando... ✅ Nota obtida
[180/201] Buscando... ✅ Nota obtida
[181/201] Buscando... ✅ Nota obtida
[182/201] Buscando... ✅ Nota obtida
[183/201] Buscando... ✅ Nota obtida
[184/201] Buscando... ✅ Nota obtida
[185/201] Buscando... ✅ Nota obtida
[186/201] Buscando... ✅ Nota obtida
[187/201] Buscando... ✅ Nota obtida
[188/201] Buscando... ✅ Nota obtida
[189/201] Buscando... ✅ Nota obtida
[190/201] Buscando... ✅ Nota obtida
[191/201] Buscando... ✅ Nota obtida
[192/201] Buscando... ✅ Nota obtida
[193/201] Buscando... ✅ Nota obtida
[194/201] Buscando... ✅ Nota obtida
[195/201] Buscando... ✅ Nota obtida
[196/201] Buscando... ✅ Nota obtida
[197/201] Buscando... ✅ Nota obtida
[198/201] Buscando... ✅ Nota obtida
[199/201] Buscando... ✅ Nota obtida
[200/201] Buscando... ✅ Nota obtida
[201/201] Buscando... ✅ Nota obtida
✅ DataFrame exportado para CSV: data\nfce_data_fetched.csv

### 1.3 Amostra da Base

In [6]:
print("Nº de Linhas e Colunas:", df_fetched.shape)
df_fetched.head()

Nº de Linhas e Colunas: (3640, 13)

,CHAVE_ANONIMIZADA,DATA,CNPJ,SUPERMERCADO,QTDE_TOTAL_NOTA,VALOR_TOTAL_NOTA,VALOR_TOTAL_TRIBUTOS,COD_PRODUTO,PRODUTO,UNIDADE,QTDE,VALOR_PRODUTO,VALOR_TOTAL_PRODUTO
0,802c078fd232a7020edc6188bd3eb95e0dad9b55e711e0...,20/02/2024 18:44:16,76.430.438/0070-01,IRMAOS MUFFATO S A,5,67.53,26.84,278018,SALG ELMA CHIPS 40G,Un,1.0,3.69,3.69
1,802c078fd232a7020edc6188bd3eb95e0dad9b55e711e0...,20/02/2024 18:44:16,76.430.438/0070-01,IRMAOS MUFFATO S A,5,67.53,26.84,278018,SALG ELMA CHIPS 40G,Un,1.0,3.69,3.69
2,802c078fd232a7020edc6188bd3eb95e0dad9b55e711e0...,20/02/2024 18:44:16,76.430.438/0070-01,IRMAOS MUFFATO S A,5,67.53,26.84,264832,SALG ELMA CH 45G,Un,1.0,3.69,3.69
3,802c078fd232a7020edc6188bd3eb95e0dad9b55e711e0...,20/02/2024 18:44:16,76.430.438/0070-01,IRMAOS MUFFATO S A,5,67.53,26.84,300337,AZEITE O LIVE 250ML,Un,1.0,21.90,21.90
4,802c078fd232a7020edc6188bd3eb95e0dad9b55e711e0...,20/02/2024 18:44:16,76.430.438/0070-01,IRMAOS MUFFATO S A,5,67.53,26.84,12440,CERV SKOL 350ML,Un,12.0,2.88,34.56

In [7]:
toc = time.time()
print(f"\n\033[33mEtapa 1 | Tempo:\033[0;0m {tictoc(tic, toc)}")

Etapa 1 | Tempo: (00:05:52) [16/06/2026 00:05:58 - 16/06/2026 00:11:50]

## 2. Preparação dos Dados

In [8]:
tic = time.time()

### 2.1 Processo de Preparação

**📦 `process_base`**

**📖 Descrição**

Função responsável por:

- processar e enriquecer a base de NFC-e
- realizar engenharia de features internas
- integrar dados externos climáticos
- padronizar produtos e unidades
- gerar dataset analítico consolidado
- ou carregar uma versão já tratada da base

dependendo do parâmetro `fetch_enabled`.

---

**⚙️ Parâmetros**

| Parâmetro | Tipo | Descrição |
|---|---|---|
| `fetch_enabled` | `bool` | Se `True`, processa os dados. Se `False`, apenas lê o `.xlsx`. |
| `df_fetched` | `pd.DataFrame` | Base bruta gerada anteriormente. |
| `raw_path` | `Path` | Caminho do arquivo final `.xlsx`. |
| `weather_enabled` | `bool` | Ativa integração climática externa. |
| `weather_output_path` | `str` | Caminho da base climática `.parquet`. |
| `latitude` | `float` | Latitude utilizada na API climática. |
| `longitude` | `float` | Longitude utilizada na API climática. |

---

**🔁 Comportamento**

**🔹 `fetch_enabled = False`**

- Lê o arquivo `.xlsx`
- Retorna a base já processada

**🔹 `fetch_enabled = True`**

Aplica as seguintes transformações:

---

**🧹 Tratamento Inicial**

**🔸 Filtragem de supermercados**

Mantém apenas:

- Condor
- Max
- Assaí

**🔸 Padronização**

- normalização de supermercados
- padronização de produtos
- padronização de unidades

---

**🕒 Feature Engineering Interno**

**🔸 Features temporais**

Criação das variáveis:

| Feature | Descrição |
|---|---|
| `MES_ANO` | Ano/mês no formato `YYYYMM` |
| `PERIODO` | MADRUGADA, MANHA, TARDE, NOITE |
| `DIA_SEMANA` | Nome do dia da semana |
| `FERIADO` | Indicador de feriado no Paraná |
| `ESTACAO_ANO` | VERAO, OUTONO, INVERNO, PRIMAVERA |

**🔸 Classificação de produtos**

Criação de:

| Feature | Descrição |
|---|---|
| `CAT_PRODUTO` | Categoria analítica do produto |

Exemplos:

- bebidas
- congelados
- bomboniere
- açougue
- hortifruti
- higiene e limpeza

**🔸 Resolução de inconsistências**

- mantém o nome mais recente por código de produto
- reduz duplicidade semântica de produtos

---

**🌦️ Integração Climática Externa**

Quando `weather_enabled=True`:

**🔸 Download automático**

Integração com:

**🌍 Open-Meteo API**

Dados históricos climáticos de Curitiba.

---

**🔸 Features climáticas**

| Feature | Descrição |
|---|---|
| `TEMPERATURA_MAX` | Temperatura máxima diária |
| `TEMPERATURA_MIN` | Temperatura mínima diária |
| `TEMPERATURA_MEDIA` | Temperatura média diária |
| `CHUVA_MM` | Volume de precipitação |
| `DIA_CHUVOSO` | Indicador booleano de chuva |
| `CAT_TEMPERATURA` | Categoria térmica do dia |

---

**🔸 Categorias de temperatura**

| Categoria |
|---|
| `MUITO_FRIO` |
| `FRIO` |
| `AMENO` |
| `QUENTE` |
| `MUITO_QUENTE` |

---

**📦 Persistência**

**🔸 Dados tratados**

Exportados em:

```text
.xlsx
```

### 2.2 Execução

In [9]:
df_trat = process_base(
    FETCH_REAL_DATA_TRAT,
    df_fetched,
    raw_path,
    WEATHER_ENABLED,
    WEATHER_OUTPUT_PATH,
    WEATHER_LATITUDE,
    WEATHER_LONGITUDE
)

Configuração de busca (nfceget): FETCH_REAL_DATA=True
✅ CNPJ filtrados: 6
✅ Supermercados normalizados: 4
✅ Datas convertidas, meses/anos únicos: 47
✅ Períodos classificados: 4
✅ Features temporais criadas
✅ Estação do ano criada
🌦 Processando dados climáticos...
🌦 Baixando dados climáticos...
✅ Dados climáticos salvos em: data\external\weather\weather_curitiba.parquet
✅ Features climáticas adicionadas
✅ Produtos padronizados: 1116
✅ Categorias classificadas: 20
✅ Unidades padronizadas: 10
✅ Nome dos produtos padronizados
✅ DataFrame final com colunas ordenadas
✅ DataFrame exportado: data\notas_fiscais_supermercado.xlsx

### 2.3 Amostra da Base

In [10]:
print("Nº de Linhas e Colunas:", df_trat.shape)
df_trat.head()

Nº de Linhas e Colunas: (3561, 25)

,chave_anonimizada,data_hora,mes_ano,dia_semana,feriado,estacao_ano,temperatura_max,temperatura_min,temperatura_media,chuva_mm,...,qtd_total_nota,valor_total_nota,valor_total_tributos,cod_produto,categoria_produto,produto,unidade,quantidade,preco_unitario,preco_total
1124,fcb669525bd643f21cb51d896c86adfe0933f5cb868f32...,2022-06-28 20:44:50,2022-06,TERCA,NAO,INVERNO,21.3,9.8,14.7,0.0,...,82,679.79,76.32,10176020001,CEREAL,CEREAL NESCAU 770G,UNIDADE,1.0,19.90,19.90
1146,fcb669525bd643f21cb51d896c86adfe0933f5cb868f32...,2022-06-28 20:44:50,2022-06,TERCA,NAO,INVERNO,21.3,9.8,14.7,0.0,...,82,679.79,76.32,11421800001,MERCEARIA,BEB VERY 1250G SALAD,UNIDADE,1.0,7.70,7.70
1147,fcb669525bd643f21cb51d896c86adfe0933f5cb868f32...,2022-06-28 20:44:50,2022-06,TERCA,NAO,INVERNO,21.3,9.8,14.7,0.0,...,82,679.79,76.32,18730001,MERCEARIA,ARR T JOAO LF T1 5kg,UNIDADE,1.0,25.90,25.90
1148,fcb669525bd643f21cb51d896c86adfe0933f5cb868f32...,2022-06-28 20:44:50,2022-06,TERCA,NAO,INVERNO,21.3,9.8,14.7,0.0,...,82,679.79,76.32,65420001,BEBIDA NAO ALCOOLICA,BEB NESQUIK 200ML MO,UNIDADE,10.0,2.89,28.90
1149,fcb669525bd643f21cb51d896c86adfe0933f5cb868f32...,2022-06-28 20:44:50,2022-06,TERCA,NAO,INVERNO,21.3,9.8,14.7,0.0,...,82,679.79,76.32,10566170001,MOLHO,EXT ELEF TP 140G,UNIDADE,2.0,2.59,5.18

In [11]:
df_trat.columns

Index(['chave_anonimizada', 'data_hora', 'mes_ano', 'dia_semana', 'feriado',
       'estacao_ano', 'temperatura_max', 'temperatura_min',
       'temperatura_media', 'chuva_mm', 'cat_temperatura', 'dia_chuvoso',
       'periodo_dia', 'cnpj', 'supermercado', 'qtd_total_nota',
       'valor_total_nota', 'valor_total_tributos', 'cod_produto',
       'categoria_produto', 'produto', 'unidade', 'quantidade',
       'preco_unitario', 'preco_total'],
      dtype='str')

In [12]:
toc = time.time()
print(f"\n\033[33mEtapa 2 | Tempo:\033[0;0m {tictoc(tic, toc)}")

Etapa 2 | Tempo: (00:00:05) [16/06/2026 00:11:50 - 16/06/2026 00:11:55]

## 3. Tempo Decorrido

In [ ]:
toc_geral = time.time()
print(f"\n\033[33mTempo decSorrido no notebook:\033[0;0m {tictoc(tic_geral, toc_geral)}")

Tempo decorrido no notebook: (00:05:57) [16/06/2026 00:05:58 - 16/06/2026 00:11:55]